### ISSUE TITLE
Отсутствует раздел /boot

### ISSUE THREAD

**Issue by click0** [mezantrop/linux2free#1]
https://github.com/mezantrop/linux2free/blob/0ae0262dc77578e093d9fc0505e34ee8a734d5c9/linux2free.sh#L199-L200

Вывод с сервера:
```
# lsblk -b -n -o KNAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,PARTLABEL
sda   disk  240057409536
sda1  part    8589934592 swap              [SWAP]
sda2  part     536870912 linux_raid_member
sda3  part  230928506880 linux_raid_member
sdb   disk  240057409536
sdb1  part    8589934592 swap              [SWAP]
sdb2  part     536870912 linux_raid_member
sdb3  part  230928506880 linux_raid_member
md1   raid1    535822336 ext3              /boot
md1   raid1    535822336 ext3              /boot
md2   raid1 230793216000 LVM2_member
md2   raid1 230793216000 LVM2_member
dm-0  lvm    12884901888 ext4              /
dm-0  lvm    12884901888 ext4              /
dm-1  lvm     8589934592 ext4              /tmp
dm-1  lvm     8589934592 ext4              /tmp
dm-2  lvm   209316741120 ext4              /home
dm-2  lvm   209316741120 ext4              /home
```
и
```
# lsblk -b -n -o KNAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,PARTLABEL | awk '$2 ~ /part/ && $4 !~ /LVM/ {print}'
sda1  part    8589934592 swap              [SWAP]
sda2  part     536870912 linux_raid_member
sda3  part  230928506880 linux_raid_member
sdb1  part    8589934592 swap              [SWAP]
sdb2  part     536870912 linux_raid_member
sdb3  part  230928506880 linux_raid_member
```
/boot нет или очень маленький.

Как пул будем создавать?
[    zpool create -f -o altroot="$freebsd_zfs" zroot $boot_disk](https://github.com/mezantrop/linux2free/blob/0ae0262dc77578e093d9fc0505e34ee8a734d5c9/linux2free.sh#L62)

**Comment by mezantrop** [comment]
В этом конкретном случае никак, но не потому, что нет /boot, а потому, что не нашли UEFI. А так, pool должен был бы создаваться из swap на sda1 - 8Г больше чем достаточно для начала. Если я ничего не накосячил, конечно.

**Comment by click0** [comment]
Про какой swap идет речь? если в коде четко сказано создавать пул из раздела с /boot.
И даже, если я делаю ZFS пул с бывшим разделом swap, то как я потом расширю пул до конца диска?

**Comment by mezantrop** [comment]
> Про какой swap идет речь? если в коде четко сказано создавать пул из раздела с /boot.

А ведь да, boot_disk может быть не определён. Спасибо учту!

>И даже, если я делаю ZFS пул с бывшим разделом swap, то как я потом расширю пул до конца диска?

Расширение пула как раз легко делается: zpool set autoexpand=on и zpool online -e может понадобиться zpool export/import сделать еще.

**Comment by mezantrop** [comment]
Fixed with https://github.com/mezantrop/linux2free/commit/f2256ef9d5c324e1b370b9404cbf2539ab35c7dd
