### ISSUE TITLE
Предлагаю двуэтапный скрипт установки FreeBSD

### ISSUE THREAD

**Issue by click0** [mezantrop/linux2free#2]
Берем [образы](https://mfsbsd.vx.sk/files/images/13/amd64/) для записи на флешку MfsBSD.

Вдумчиво читаем инструкции, как записать RouterOS на виртуалку.
1. https://www.digitalocean.com/community/questions/installing-mikrotik-routeros
2. https://gist.github.com/stroebs/54fc09734a3911e91eeeb43434f117df

Монтируем в память /tmp раздел, на него же пишем наш образ MfsBSD.
Выбираем раздел swap раздел или внаглую в /dev/(sda|vda) записываем образ.
Сетевые настройки внутрь  MfsBSD можно передать:
1.  монтирование образа и правкой конфигов
2.  через grub2 и модуль kfreebsd
3.  через grub2, grub-imageboot и kfreebsd .

Все без использования UEFI.
 
P.S. у меня сетевые настройки передаются третим способом

**Comment by mezantrop** [comment]
Ну, собственно, да, mfsbsd/linuxbsd никто не отменял. Надо будет в README.md указать вместе  с Depenguinator в качестве альтернатив. Спасибо!
